name: Compile Kernel

on:
  workflow_dispatch:
    inputs:
      clang_version:
        description: Type the clang version of ur kernel
        required: true
        type: choice
        options:
          - clang-3289846
          - clang-r450784e
          - clang-r475365b
          - clang-r487747c
          - clang-r498229b
          - clang-r510928
          - clang-r547379
          - clang-r563880
          - clang-r563880c
          - clang-r574158
          - clang-stable

      kernel_source:
        description: Kernel Source Repo URL
        required: true
        type: string

      kernel_branch:
        description: Kernel Branch
        required: true
        type: string

      defconfig_name:
        description: Defconfig Name
        required: true
        type: string

      device_codename:
        description: Device Codename (e.g. marble, alioth, vayu)
        required: true
        type: string

      ksu_type:
        description: "KernelSU Version"
        required: true
        type: choice
        options:
          - None
          - KernelSU-by-xx
          - ReSukiSU-with-susfs

jobs:
  Kernel_CI:
    env:
        GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          bc bison flex \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          build-essential \
          lz4 \
          git \
          python3 \
          curl \
          dwarves \
          cpio \
          gcc-aarch64-linux-gnu
          
      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b ${{ inputs.kernel_branch }} ${{ inputs.kernel_source }} kernel

      - name: Download AOSP Clang
        run: |
          mkdir -p toolchains/${{ inputs.clang_version }}
          cd toolchains
          OLD_TAGS=("clang-r450784e" "clang-r475365b" "clang-r487747c" "clang-r498229b" "clang-r510928")
          if [[ " ${OLD_TAGS[@]} " =~ " ${{ inputs.clang_version }} " ]]; then
            echo "Downloading from android-14.0.0_r33"
            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-14.0.0_r33/${{ inputs.clang_version }}.tar.gz
          else
            echo "Downloading from android16-qpr2-release"
            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/${{ inputs.clang_version }}.tar.gz
          fi
          tar -xf "${{ inputs.clang_version }}.tar.gz" -C ${{ inputs.clang_version }}

      - name: Compile Kernel
        run: |
          CLANG_ROOT="${GITHUB_WORKSPACE}/toolchains/${{ inputs.clang_version }}/bin"
          export PATH="${CLANG_ROOT}:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CC="${CLANG_ROOT}/clang"
          export CXX="${CLANG_ROOT}/clang++"
          export HOSTCC="${CLANG_ROOT}/clang"
          export HOSTCXX="${CLANG_ROOT}/clang++"
          export LD="${CLANG_ROOT}/ld.lld"
          export AR="${CLANG_ROOT}/llvm-ar"
          export NM="${CLANG_ROOT}/llvm-nm"
          export OBJCOPY="${CLANG_ROOT}/llvm-objcopy"
          export OBJDUMP="${CLANG_ROOT}/llvm-objdump"
          export STRIP="${CLANG_ROOT}/llvm-strip"
          export CROSS_COMPILE=aarch64-linux-gnu-
          cd kernel
          case "${{ inputs.ksu_type }}" in
            "KernelSU-by-xx")
              curl -LSs "https://raw.githubusercontent.com/backslashxx/KernelSU/refs/heads/master/kernel/setup.sh" | bash -s master
              ;;
            "ReSukiSU-with-susfs")
              curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash -s main
              ;;
          esac
          touch ./.scmversion
          
          if [[ "${{ inputs.ksu_type }}" == *susfs ]]; then
            curl -Lo susfs.patch https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Patch/susfs_patch_to_4.14.patch
            curl -Lo inline.sh https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/susfs_inline_hook_patches.sh
            patch -p1 < susfs.patch
            bash inline.sh
            
            echo "CONFIG_KSU=y" >> arch/arm64/configs/${{ inputs.defconfig_name }}
            echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/${{ inputs.defconfig_name }}
          fi
          
          make O=out ${{ inputs.defconfig_name }}
          
          if [[ "${{ inputs.ksu_type }}" == "KernelSU-by-xx" ]]; then
            echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y" >> out/.config
          fi
          
          make -j$(nproc) O=out 

      - name: Make AnyKernel3
        run: |
          ZIP_NAME="${{ inputs.device_codename }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
          BOOT_DIR="kernel/out/arch/arm64/boot"
          git clone https://github.com/Kernel-SU/AnyKernel3.git
          
          # Priority logic for Kernel Image
          if [ -f $BOOT_DIR/Image.gz-dtb ]; then
              echo "Found Image.gz-dtb, using it."
              cp $BOOT_DIR/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [ -f $BOOT_DIR/Image.gz ]; then
              echo "Image.gz-dtb not found, using Image.gz."
              cp $BOOT_DIR/Image.gz AnyKernel3/Image.gz
          fi

          # Optional DTBO handling
          if [ -f $BOOT_DIR/dtbo.img ]; then
              echo "dtbo.img found, adding to AnyKernel."
              cp $BOOT_DIR/dtbo.img AnyKernel3/dtbo.img
          fi

          cd AnyKernel3
          sed -i "s|ksu_supported=false|ksu_supported=true|" anykernel.sh
          zip -r9 ../"${ZIP_NAME}.zip" * -x .git

      - name: Create GitHub Release
        run: |
          REL_NAME="${{ inputs.device_codename }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
          cd ${GITHUB_WORKSPACE}
          ZIP_FILE=$(ls *.zip)
          BOOT_DIR="kernel/out/arch/arm64/boot"
          EXTRA_FILES=""
          for img in Image Image.gz Image.gz-dtb; do
            if [ -f "${BOOT_DIR}/${img}" ]; then
              cp "${BOOT_DIR}/${img}" "${GITHUB_WORKSPACE}/${img}"
              EXTRA_FILES="${EXTRA_FILES} ${img}"
            fi
          done
          gh release create "$REL_NAME" --title "$REL_NAME" --notes "" "${ZIP_FILE}" ${EXTRA_FILES}
